ipc = on
splash = false

wallpaper {
  monitor = HDMI-A-1
  path = /home/hiroki/.config/hypr/conf/wallpapers/pexels-sean-whang-804269.jpg
  # fit_mode = cover   # 好みで。古い版だと未対応のこともあるので、まずはコメントのまま
}

wallpaper {
  monitor = HDMI-A-2
  path = /home/hiroki/.config/hypr/conf/wallpapers/pexels-sean-whang-804269.jpg
  # fit_mode = cover
}

